name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Fetch all tags
      run: git fetch --force --tags
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    
    - name: Module init
      run: |
        go mod init github.com/nigelhoneycutt/sslmux
        go mod tidy
    
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        # either 'goreleaser' (default) or 'goreleaser-pro'
        distribution: goreleaser
        version: latest
        args: release --rm-dist --config .github/goreleaser.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    
    # - name: Checkout code
    #   uses: actions/checkout@v2

    # - name: Set up Go
    #   uses: actions/setup-go@v1
    #   with:
    #     go-version: 1.18

    # - name: Setup files
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    #   run: |
    #     echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
    #     sudo apt update && sudo apt install -y goreleaser

    #     goreleaser release --config .github/goreleaser.yml
