name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.18

    - name: Setup files
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
        sudo apt update && sudo apt install -y goreleaser
        go mod init github.com/nigelhoneycutt/sslmux
        go mod tidy
        goreleaser release --config .github/goreleaser.yml
