name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Setup files
      run: |
        sudo apt update && sudo apt install -y musl-*
        go mod init github.com/nigelhoneycutt/sslmux
        go mod tidy
        
    - name: goreleaser
      if: success()
      uses: docker://goreleaser/goreleaser:latest
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        args: release --config .github/goreleaser.yml
